BarTemperatureLoad Implementation
BHoM/SAP2000_Toolkit pull request #143
Opened 2020-09-09 19:59 UTC by jean-lucjacksonBH

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #141 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/SAP2000_Toolkit/141%20-%20Issue%20-%20BarTemperatureLoad?csf=1&web=1&e=IWVUdc

### Changelog

### Additional comments

2020-09-09 20:00 UTC, jean-lucjacksonBH commented
/azp run SAP2000_Toolkit.CheckInstaller

2020-09-24 07:52 UTC, FraserGreenroyd commented
@jean-lucjacksonBH @JosefTaylor can we add labels to categorise this PR please :smile:

2020-10-07 14:54 UTC, JosefTaylor requested changes
Looks good. you can simplify the create a little by taking out replaceNow and just using replace- that's for looping over the directions in a 3D load.

2020-10-07 14:54 UTC, JosefTaylor commented on SAP2000_Adapter/CRUD/Create/Loads.cs
> +                bool replaceNow = replace;
should be able to leave off replaceNow - only necessary for looping over directions when you've got a 3d load.

2020-10-29 22:19 UTC, JosefTaylor approved these changes

2020-10-29 22:19 UTC, JosefTaylor commented
The changes look good- needs a proper test though.

2020-11-04 00:07 UTC, maryannewachter commented
Fixed AdapterIdReferences and checked with test files. Works as expected.

2020-11-04 00:11 UTC, maryannewachter approved these changes

2020-11-04 08:03 UTC, IsakNaslundBh commented
Do not think we will be able to merge this in after all the merges that have happened:
https://github.com/BHoM/SAP2000_Toolkit/network

![image](https://user-images.githubusercontent.com/22005920/98084452-19a5b400-1e7c-11eb-8fca-37932a82a192.png)

Think the things going on in there are a bit to much to handle with a manual rebase and conflict fixing, also looking at the changed files, there are multiple flagging up there as additions that already are on the master.

Would suggest to start this over from scratch in a github sense, that is, start from a new branch from master and add in any code written in here to that branch. Manually, not by merging this PR branch into it or similar, cause big risk it could lead to similar situation.

2020-11-04 17:08 UTC, JosefTaylor commented
Closing this in favor of #160

2020-11-04 17:08 UTC, closed without merging