Add implementation of Exit command
BHoM/SAP2000_Toolkit pull request #239
Opened 2021-08-19 15:50 UTC by IsakNaslundBh

### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/303

 ### Issues addressed by this PR

 Closes #238 

 

Adding support for the Exit command

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EjpTgU6jo_tJr30rbJs0a_gBnZnhI1rYcv3aQ-Yc3A6E2g?e=fenJ0J

 ### Changelog

 ### Additional comments

2021-08-24 14:13 UTC, JosefTaylor submitted a review, later dismissed
Looks great, works as expected.

2021-08-24 14:14 UTC, JosefTaylor commented
@BHoMBot check required

2021-08-24 14:14 UTC, JosefTaylor commented
@BHoMBot check copyright-compliance

2021-08-24 14:15 UTC, JosefTaylor commented
@BHoMBot check dataset-compliance

2021-08-24 14:15 UTC, JosefTaylor commented
@BHoMBot check ready-to-merge

2021-08-31 11:06 UTC, IsakNaslundBh commented
After discussions in https://github.com/BHoM/Robot_Toolkit/pull/466#issuecomment-904922155 Added check for if file path existed before trying to exit if the `SaveBeforeClose` option is true

2021-08-31 11:07 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-09-01 07:43 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-09-02 13:52 UTC, JosefTaylor requested changes
Almost works!

2021-09-02 13:52 UTC, JosefTaylor commented on SAP2000_Adapter/AdapterActions/Execute.cs
> +                if (m_app.SapModel.GetModelFilepath() == "(Untitled)")
```suggestion
                if (m_app.SapModel.GetModelFilename() == "(Untitled)")
```

2021-09-02 13:52 UTC, JosefTaylor commented on SAP2000_Adapter/AdapterActions/Execute.cs
> +                if (m_app.SapModel.GetModelFilepath() == "(Untitled)")
Need just the file name, not full path. I tested with this change and it works properly, failing to close the file and throwing the desired error in Grasshopper. Without it, the error is never hit, and SAP2000 throws up a dialogue about failing to save, then closes after the user accepts.

2021-09-07 15:31 UTC, IsakNaslundBh commented
@BHoMBot check required

2021-09-07 15:35 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2021-09-07 17:23 UTC, JosefTaylor commented on SAP2000_Adapter/AdapterActions/Execute.cs
> +                if (m_app.SapModel.GetModelFilepath() == "(Untitled)")
GetModelFilepath() returns "" rather than "(Untitled)", cancelling my comment.

2021-09-07 17:24 UTC, JosefTaylor approved these changes

2021-09-07 17:24 UTC, JosefTaylor commented
@BHoMBot check ready-to-merge

2021-09-08 07:17 UTC, merged